version: "3.4"
services:
  statsd:
    #image: StatsD:test1
    build: ./ 
    container_name: StatsD_client
    restart: unless-stopped
    environment:
      - DD_AGENT_HOST=${DD_AGENT_HOST}
    #networks:
      #- test-docker-net
    
  datadog:
    container_name: datadog-agent
    image: datadog/agent:latest
    environment:
      ## GLOBALS
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_HOSTNAME=docker.sandbox
      - DD_TAGS=reason:statsd_test tag_test:yes
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_DOCKER_LABELS_AS_TAGS=true
      - DD_DOCKER_ENV_AS_TAGS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    ports:
      - "8125:8125/udp"
    #networks:
     # - test-docker-net # Created with docker network create test-docker-net and deleted with docker network rm test-docker-net
    
#networks:
 # test-docker-net:
  #  external: true